### ISSUE TITLE
[Request] Binary and instructions for inclusion

### ISSUE THREAD

**Issue by ArcadeTV** [viciious/SegaCDMode1PCM#1]
Thank you very much for your effort and time to release this driver!
I'd like to ask if you could provide a binary that can easily be included into roms and would be usuable without any C or compiling.
Maybe even with some kind of interface like the msu-md driver. I was thinking about something like this:

```
SegaCDMode1PCM:
    incbin "SegaCDMode1PCM.bin"

initDriver:
    jsr SegaCDMode1PCM
    rts
```

And then just setting the appropriate registers to trigger functions with given values.

**Comment by viciious** [comment]
I could certainly provide a compiled binary file for the driver, however, none of the other suggestions would actually work.

**Comment by ArcadeTV** [comment]
Thank You, I totally understand. It's not meant to be used that way. 
But if someone wanted to use the driver in a romhack, do you maybe have some suggestions how to work with it when C is not in this person's skillset?

**Comment by viciious** [comment]
I'm not sure I understand what's so specific about calling C functions that requires a certain skillset. I mean, it's just something akin to this:

```
        move.l  #0,-(sp)            /* autoloop */
        move.l  d3,-(sp)            /* vol */
        move.l  d2,-(sp)            /* pan */ 
        move.l  #0,-(sp)            /* freq */
        move.l  d1,-(sp)            /* buf id */
        move.l  d0,-(sp)            /* src id */

        jsr     scd_play_src
        lea     24(sp),sp
```

**Comment by ArcadeTV** [comment]
Since I'm not an expert, I may have troubles asking the right questions.
Thank you for this example!
